### ISSUE TITLE
inference error

### ISSUE THREAD

**Issue by tan90xx** [BUTSpeechFIT/DiariZen#4]
I would like to express my sincere gratitude for sharing the code on GitHub. It's really helpful.
However, I've encountered a bug. When I run the `infer_avg.py`, I get the following error message:
```
Traceback (most recent call last):
  File "/opt/tiger/laps/Diarization/DiariZen/recipes/diar_ssl/infer_avg.py", line 412, in <module>
    c_result = diarize_session(
  File "/opt/tiger/laps/Diarization/DiariZen/recipes/diar_ssl/infer_avg.py", line 108, in diarize_session
    count = pipeline.speaker_count(
  File "/opt/tiger/laps/Diarization/DiariZen/pyannote-audio/pyannote/audio/pipelines/utils/diarization.py", line 148, in speaker_count
    count = Inference.aggregate(
  File "/opt/tiger/laps/Diarization/DiariZen/pyannote-audio/pyannote/audio/core/inference.py", line 559, in aggregate
    duration=frames.duration,
AttributeError: 'function' object has no attribute 'duration'
```
Could you please take a look at this issue and give some advice on how to fix it? Thank you very much!

**Comment by jyhan03** [comment]
Hi, did you use the correct Pyannote version (from this repo)?

**Comment by tan90xx** [comment]
Yes, it's loading from local path `DiariZen/pyannote-audio/pyannote/audio` (from this repo).

**Comment by jyhan03** [comment]
Hi, I just cloned the code and re-ran the inference but everything went well on my part. 
Could you try to re-install the code?

**Comment by tan90xx** [comment]
Hi,

I tried reinstalling the code as you suggested, and it resolved the issue.

It seems the problem was related to network restrictions in China. Previously, I had to manually download files from GitHub and HuggingFace to my local machine and then upload them to the server. Now, I’m using a server with direct access to the internet, which has made things much smoother.

For anyone facing a similar issue, modifying [#L64](https://github.com/BUTSpeechFIT/DiariZen/blob/main/recipes/diar_ssl/run_stage.sh#L64) to `embedding_model=pyannote/wespeaker-voxceleb-resnet34-LM` avoids the following error:
```Shell
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/YOUR_PATH/pretrained/pyannote3/wespeaker-voxceleb-resnet34-LM/pytorch_model.bin'. Use 'repo_type' argument if needed.
```

Thanks again for your help!

**Comment by jyhan03** [comment]
> Hi,
> 
> I tried reinstalling the code as you suggested, and it resolved the issue.
> 
> It seems the problem was related to network restrictions in China. Previously, I had to manually download files from GitHub and HuggingFace to my local machine and then upload them to the server. Now, I’m using a server with direct access to the internet, which has made things much smoother.
> 
> For anyone facing a similar issue, modifying [#L64](https://github.com/BUTSpeechFIT/DiariZen/blob/main/recipes/diar_ssl/run_stage.sh#L64) to `embedding_model=pyannote/wespeaker-voxceleb-resnet34-LM` avoids the following error:
> 
> ```shell
> huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/YOUR_PATH/pretrained/pyannote3/wespeaker-voxceleb-resnet34-LM/pytorch_model.bin'. Use 'repo_type' argument if needed.
> ```
> 
> Thanks again for your help!

You're welcome and good luck!
